version: "3"
services:
  tvheadend:
    image: 4gray/iptvnator:latest
    container_name: tvheadend
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.tvheadend.tls=true
      - traefik.http.routers.tvheadend.rule=Host(`iptv.roshamagin.site`)
      - traefik.http.routers.tvheadend.entrypoints=websecure
      - traefik.http.routers.tvheadend.tls.certresolver=myresolver
      - traefik.http.services.tvheadend.loadbalancer.server.port=9981

networks:
  public:
    external: true
