version: "3"
services:
  iptv-proxy:
    image: ghcr.io/romaxa55/iptv-proxy/iptv-proxy:latest
#     build:
#       context: .
#       dockerfile: Dockerfile
    volumes:
      - ./iptv:/root/iptv
    container_name: iptv-proxy
    restart: on-failure
    env_file: .env
    environment:
      USER: ${USER_NAME:-test}
      PASSWORD: ${PASSWORD:-password}
    labels:
      - traefik.enable=true
      - traefik.http.routers.iptv-proxy.tls=true
      - traefik.http.routers.iptv-proxy.rule=Host(`iptv.roshamagin.site`)
      - traefik.http.routers.iptv-proxy.entrypoints=websecure
      - traefik.http.routers.iptv-proxy.tls.certresolver=myresolver
      - traefik.http.services.iptv-proxy.loadbalancer.server.port=443
